spring:
  application:
    name: Produtos-API
  datasource:
    url: jdbc:h2:mem:produtos #aqui estamos configurando nosso banco em memoria e dizendo que seu nome é produto.
    username: sa #nome padrão do banco
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console # caminho padrão porem pode ser alterado